### PR TITLE
pull request raised for quality of code checking by my coding-partner

### PR DESCRIPTION
**Pull request by pratap-panabaka**
this PR is for checking quality of code by my coding-partner to see if I followed below.

[JavaScript best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).
[DRY, KISS, and YAGNI](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/clean-code/lesson_DRY_KISS_YAGNI.md) rules.
[HTML and CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

### CODE REVIEW

**Review by David-Kasilia — CHANGES_REQUESTED** [review]
# **Hello @PRATAP-KUMAR ✋**
I am Your coding partner @David-Kasilia. I am reviewing your PR.
Good job so far!🔥🔥🔥
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
I really appreciate your huge efforts 💪🏻💪🏻👌🏻👌🏻

## **Highlights ✨✨**
- Great job setting up the correct linters ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## **Changes Required**
- Kindly try to follow the best JavaScript to extend your codebase ♻️⛔️
- Kindly try to work on styling your project for a good user interface ♻️⛔️
- Kindly try implementing the editing feature to the to-do list as it increases the user experience ♻️⛔️

Great Work @PRATAP-KUMAR 👏👏👏
Cheers and Happy coding!👏👏👏

**Comment by pratap-panabaka** [comment]
Hi @David-Kasilia thank you for your review and valuable points, I am now working on considering your comments. Will ping you back once I am done. Thank You.

**Review by David-Kasilia — APPROVED** [review]
# **Hello @PRATAP-KUMAR ✋**
I am Your coding partner @David-Kasilia. I am reviewing your PR.
Your project is complete! There is nothing else to say other than... it's time to merge it. 💯 
Congratulations! 🥳 🎉

## **Highlights**
- Great job setting up the correct linters ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️
- Good Deployment of the project ✔️
- Your code has no repetition of code therefore your code is DRY✔️
- Your code is kept simple and that is very nice therefore your code is KISS ✔️
- There is no unnecessary code implemented on your code nice work (YAGNI)✔️

## **[Optional] suggestions**
- Kindly try to improve the User Experience for the website by avoiding the reloading of the page when a task is added. This will make it simple for the users to use the website. ♻️⛔️


Great Work @PRATAP-KUMAR 👏👏👏
Cheers and Happy coding!👏👏👏

**Comment by pratap-panabaka** [comment]
Sure @David-Kasilia I will implement that.

**Pull request merged**
